version: '3'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.PHP
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile.mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
